# Generated by Django 5.2.14 on 2026-06-12 04:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementAnalysis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when this record was first persisted.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the most recent save.', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avg_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('salary_credits_detected', models.BooleanField(default=False)),
                ('bounce_count', models.PositiveIntegerField(default=0)),
                ('analysis_data', models.JSONField(blank=True, default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_analyses', to='applications.loanapplication')),
            ],
            options={
                'verbose_name_plural': 'Bank statement analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudCheck',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when this record was first persisted.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the most recent save.', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(max_length=50)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('review', 'Review')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_checks', to='applications.loanapplication')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when this record was first persisted.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the most recent save.', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('dti_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('assessment_data', models.JSONField(blank=True, default=dict)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='applications.loanapplication')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditBureauReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when this record was first persisted.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the most recent save.', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bureau', models.CharField(choices=[('cibil', 'CIBIL'), ('experian', 'Experian'), ('crif', 'CRIF')], max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('raw_response_ref', models.CharField(blank=True, max_length=255)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('pulled_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureau_reports', to='applications.loanapplication')),
                ('pulled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pulled_at'],
                'indexes': [models.Index(fields=['application', 'bureau'], name='underwritin_applica_260dd8_idx')],
            },
        ),
    ]
