# Generated by Django 5.2.14 on 2026-06-12 04:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSanctionTarget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when this record was first persisted.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the most recent save.', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanction_targets', to='organization.branch')),
            ],
            options={
                'verbose_name': 'Branch Sanction Target',
                'verbose_name_plural': 'Branch Sanction Targets',
                'ordering': ['-period_year', '-period_month', 'branch__branch_name'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'period_year', 'period_month'), name='uniq_branch_sanction_target_period'), models.CheckConstraint(condition=models.Q(('period_month__gte', 1), ('period_month__lte', 12)), name='branch_sanction_target_valid_month')],
            },
        ),
        migrations.CreateModel(
            name='OfficerSanctionTarget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when this record was first persisted.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the most recent save.', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanction_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Officer Sanction Target',
                'verbose_name_plural': 'Officer Sanction Targets',
                'ordering': ['-period_year', '-period_month', 'officer__first_name'],
                'constraints': [models.UniqueConstraint(fields=('officer', 'period_year', 'period_month'), name='uniq_officer_sanction_target_period'), models.CheckConstraint(condition=models.Q(('period_month__gte', 1), ('period_month__lte', 12)), name='officer_sanction_target_valid_month')],
            },
        ),
    ]
