def _pdf_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def build_simple_pdf(lines: list[str]) -> bytes:
    """Minimal single-page PDF used as the Digio e-sign source document."""
    content_ops = ["BT", "/F1 11 Tf", "50 740 Td"]
    first = True
    for line in lines:
        if not first:
            content_ops.append("0 -16 Td")
        content_ops.append(f"({_pdf_escape(line)}) Tj")
        first = False
    content_ops.append("ET")
    stream = "\n".join(content_ops).encode("latin-1", errors="replace")

    objects = [
        b"1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj",
        b"2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj",
        (
            b"3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            b"/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >> endobj"
        ),
        f"4 0 obj << /Length {len(stream)} >> stream\n".encode() + stream + b"\nendstream endobj",
        b"5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj",
    ]

    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for obj in objects:
        offsets.append(len(out))
        out.extend(obj)
        out.extend(b"\n")
    xref_pos = len(out)
    out.extend(f"xref\n0 {len(objects) + 1}\n".encode())
    out.extend(b"0000000000 65535 f \n")
    for offset in offsets:
        out.extend(f"{offset:010d} 00000 n \n".encode())
    out.extend(
        (
            f"trailer << /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_pos}\n%%EOF\n"
        ).encode()
    )
    return bytes(out)


def build_agreement_pdf(*, lead) -> bytes:
    customer = lead.customer
    amount = getattr(lead, "required_amount", None)
    amount_text = f"{amount}" if amount is not None else "as per application"
    return build_simple_pdf(
        [
            "Loan Agreement (sandbox e-sign)",
            f"Lead ID: {lead.lead_id}",
            f"Customer: {customer.full_name}",
            f"Email: {customer.email}",
            f"Mobile: {customer.mobile_number}",
            f"Requested amount: {amount_text}",
            "This document is generated by LMS for Digio sandbox signing.",
        ]
    )
