# Generated by Django 5.2.14 on 2026-06-12 04:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(db_index=True)),
                ('transaction_type', models.CharField(choices=[('disbursement', 'Disbursement'), ('fee', 'Processing Fee'), ('interest', 'Interest'), ('repayment', 'Repayment'), ('penalty', 'Penalty'), ('reversal', 'Reversal'), ('settlement', 'Settlement'), ('writeoff', 'Write Off')], max_length=20)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('narration', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Loan ledger entries',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
