# Generated by Django 5.2.14 on 2026-06-12 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanledgerentry',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='loans.loan'),
        ),
        migrations.AddIndex(
            model_name='loanledgerentry',
            index=models.Index(fields=['loan', '-created_at'], name='ledger_loan_loan_id_6b0386_idx'),
        ),
        migrations.AddIndex(
            model_name='loanledgerentry',
            index=models.Index(fields=['loan', '-transaction_date'], name='ledger_loan_loan_id_1d5ec3_idx'),
        ),
        migrations.AddConstraint(
            model_name='loanledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('debit_amount__gte', 0), ('credit_amount__gte', 0)), name='ledger_amounts_non_negative'),
        ),
    ]
