# Generated by Django 5.2.14 on 2026-06-12 04:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable role e.g. Relationship Manager.', max_length=100, unique=True, verbose_name='Role name')),
                ('slug', models.SlugField(help_text='Machine identifier for seeding and integrations.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this user.', primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Primary login identifier. Must be unique across the system.', max_length=254, unique=True, verbose_name='Email address')),
                ('first_name', models.CharField(help_text='Given name as per official records.', max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, help_text='Family name as per official records.', max_length=150, verbose_name='Last name')),
                ('mobile_number', models.CharField(blank=True, db_index=True, help_text='E.164 or local format mobile for OTP and notifications.', max_length=20, verbose_name='Mobile number')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user can log in.', verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, help_text='Grants access to Django admin. Does not imply loan permissions.', verbose_name='Staff status')),
                ('is_verified', models.BooleanField(default=False, help_text='True after email/phone verification for regulated actions.', verbose_name='Verified')),
                ('last_login', models.DateTimeField(blank=True, help_text='Timestamp of the most recent successful authentication.', null=True, verbose_name='Last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('customer', 'Customer'), ('loan', 'Loan'), ('document', 'Document'), ('dashboard', 'Dashboard'), ('report', 'Report'), ('user', 'User'), ('role', 'Role'), ('workflow', 'Workflow'), ('call_log', 'Call Log'), ('field_investigation', 'Field Investigation'), ('collection', 'Collection'), ('permission', 'Permission'), ('audit', 'Audit')], help_text='Functional area this permission applies to.', max_length=50, verbose_name='Module')),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('assign', 'Assign'), ('upload', 'Upload'), ('download', 'Download'), ('disburse', 'Disburse'), ('export', 'Export'), ('sanction', 'Sanction'), ('verify', 'Verify'), ('grant', 'Grant'), ('revoke', 'Revoke')], help_text='Operation allowed within the module.', max_length=50, verbose_name='Action')),
                ('code', models.CharField(db_index=True, editable=False, help_text='Auto-generated as module.action (e.g. loan.approve).', max_length=100, unique=True, verbose_name='Permission code')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'indexes': [models.Index(fields=['module', 'action'], name='accounts_pe_module_274548_idx')],
                'constraints': [models.UniqueConstraint(fields=('module', 'action'), name='unique_permission_module_action')],
            },
        ),
        migrations.CreateModel(
            name='PermissionChangeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('grant', 'Grant'), ('revoke', 'Revoke')], max_length=20)),
                ('approval_email', models.FileField(upload_to='permission_approvals/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_changes_performed', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_records', to='accounts.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_change_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Change Record',
                'verbose_name_plural': 'Permission Change Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleChangeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('assign', 'Assign'), ('revoke', 'Revoke')], max_length=20)),
                ('approval_email', models.FileField(upload_to='role_approvals/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_changes_performed', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_records', to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_change_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Change Record',
                'verbose_name_plural': 'Role Change Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
            },
        ),
        migrations.CreateModel(
            name='RolePermissionChangeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('grant', 'Grant'), ('revoke', 'Revoke')], max_length=20)),
                ('approval_email', models.FileField(upload_to='role_permission_approvals/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_permission_changes_performed', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_change_records', to='accounts.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_change_records', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Role Permission Change Record',
                'verbose_name_plural': 'Role Permission Change Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_grants', to='accounts.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_assigned', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='accounts_us_email_f69303_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='accounts_us_created_4734df_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email', ''), _negated=True), name='accounts_user_email_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='userpermission',
            constraint=models.UniqueConstraint(fields=('user', 'permission'), name='unique_user_permission'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='unique_user_role'),
        ),
    ]
