# Generated by Django 5.2.16 on 2026-08-04 05:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_application_interested_documents_received'),
        ('organization', '0004_salary_banks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionSalaryBank',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when this record was first persisted.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the most recent save.', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(blank=True, default='', max_length=50)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanction_salary_links', to='organization.bank')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_bank_links', to='applications.applicationdecision')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('decision', 'bank'), name='uniq_sanction_salary_bank_per_decision')],
            },
        ),
    ]
