# Generated by Django 5.2.15 on 2026-06-12 11:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_update_lead_and_call_disposition_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when this record was first persisted.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the most recent save.', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('residential', 'Residential'), ('office', 'Office'), ('permanent', 'Permanent'), ('current', 'Current'), ('correspondence', 'Correspondence')], max_length=30)),
                ('pincode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified')], default='unverified', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='leads.lead')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadCompanyDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when this record was first persisted.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the most recent save.', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified')], default='unverified', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='leads.lead')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadEsignRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when this record was first persisted.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the most recent save.', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('signed', 'Signed'), ('expired', 'Expired')], default='sent', max_length=20)),
                ('document_label', models.CharField(default='Loan Agreement Pack', max_length=255)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('signed_file', models.FileField(blank=True, upload_to='lead_esign/%Y/%m/')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esign_requests', to='leads.lead')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esign_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadReference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when this record was first persisted.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the most recent save.', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('spouse', 'Spouse'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('other', 'Other')], max_length=30)),
                ('reference_name', models.CharField(max_length=255)),
                ('reference_mobile', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='leads.lead')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadVideoKycRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when this record was first persisted.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the most recent save.', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('completed', 'Completed'), ('expired', 'Expired')], default='sent', max_length=20)),
                ('session_label', models.CharField(default='Video KYC Session', max_length=255)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recording_file', models.FileField(blank=True, upload_to='lead_video_kyc/%Y/%m/')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_kyc_requests', to='leads.lead')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_kyc_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when this record was first persisted.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the most recent save.', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('cibil_report', 'Cibil Report'), ('bank_statement', 'Bank Statement'), ('photograph', 'Selfie'), ('salary_slip', 'Salary Slip'), ('id_card', 'ID Card'), ('cheque', 'Cheque'), ('electricity_bill', 'Electricity Bill'), ('mobile_bill', 'Mobile Bill'), ('others', 'Others')], max_length=50)),
                ('file', models.FileField(upload_to='lead_documents/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified')], default='unverified', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads.lead')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', 'document_type'], name='leads_leadd_lead_id_2c1705_idx')],
            },
        ),
    ]
