# Generated by Django 5.2.15 on 2026-06-17 18:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0005_leadvideokycrequest_session_details"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leadcompanydetail",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="leadcompanydetail",
            name="lead",
        ),
        migrations.RemoveField(
            model_name="leadcompanydetail",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="leaddocument",
            name="created_by",
        ),
        migrations.RemoveIndex(
            model_name="leaddocument",
            name="leads_leadd_lead_id_2c1705_idx",
        ),
        migrations.RemoveField(
            model_name="leaddocument",
            name="lead",
        ),
        migrations.RemoveField(
            model_name="leaddocument",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="leadreference",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="leadreference",
            name="lead",
        ),
        migrations.RemoveField(
            model_name="leadreference",
            name="updated_by",
        ),
        migrations.CreateModel(
            name="LeadFollowUpRemark",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="UTC timestamp when this record was first persisted.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="UTC timestamp of the most recent save.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("remark_category", models.CharField(max_length=100)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("priority", models.CharField(max_length=20)),
                ("notes", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_follow_up_remarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_up_remarks",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="LeadAddress",
        ),
        migrations.DeleteModel(
            name="LeadCompanyDetail",
        ),
        migrations.DeleteModel(
            name="LeadDocument",
        ),
        migrations.DeleteModel(
            name="LeadReference",
        ),
    ]
