# Generated by Django 5.2.14 on 2026-06-24 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_follow_up_remark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='disposition',
            field=models.CharField(choices=[('busy', 'Busy'), ('call_disconnected', 'Call Disconnected'), ('call_me_later', 'Call Me Later'), ('call_you_later', 'Call You Later'), ('dnd', 'DND'), ('duplicate_lead', 'Duplicate Lead'), ('follow_up_required', 'Follow Up Required'), ('interested', 'Interested'), ('invalid_number', 'Invalid Number'), ('no_answer', 'No Answer'), ('not_interested', 'Not Interested'), ('switched_off', 'Switched Off'), ('other', 'Other')], max_length=30),
        ),
        migrations.CreateModel(
            name='LeadStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when this record was first persisted.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the most recent save.', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, default='', max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_status_changes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Lead Status History',
                'verbose_name_plural': 'Lead Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
