# Generated by Django 5.2.16 on 2026-07-28 05:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_companyaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankHoliday',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when this record was first persisted.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the most recent save.', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holiday_date', models.DateField(db_index=True)),
                ('holiday_name', models.CharField(max_length=255)),
                ('financial_year_start', models.PositiveSmallIntegerField(db_index=True, help_text='Calendar year when the financial year begins (e.g. 2025 for FY 2025-26).')),
            ],
            options={
                'verbose_name': 'Bank Holiday',
                'verbose_name_plural': 'Bank Holidays',
                'ordering': ['-financial_year_start', 'holiday_date'],
            },
        ),
        migrations.RenameIndex(
            model_name='companyaccount',
            new_name='organizatio_is_acti_a0a097_idx',
            old_name='organizatio_is_acti_8a1f2c_idx',
        ),
        migrations.AddField(
            model_name='bankholiday',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='bankholiday',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddConstraint(
            model_name='bankholiday',
            constraint=models.UniqueConstraint(fields=('financial_year_start', 'holiday_date'), name='uniq_bank_holiday_fy_date'),
        ),
    ]
