# Generated by Django 5.2.14 on 2026-06-29 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_delete_companyaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customerbankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('account_hash', ''), _negated=True), fields=('account_hash',), name='unique_customer_bank_account_hash'),
        ),
    ]
