# Generated by Django 5.2.14 on 2026-06-12 04:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when this record was first persisted.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the most recent save.', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('min_tenure', models.PositiveIntegerField(help_text='Minimum tenure in tenure_unit.')),
                ('max_tenure', models.PositiveIntegerField(help_text='Maximum tenure in tenure_unit.')),
                ('tenure_unit', models.CharField(choices=[('days', 'Days'), ('months', 'Months')], default='days', max_length=10)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('interest_calculation', models.CharField(choices=[('flat', 'Flat'), ('reducing', 'Reducing Balance')], default='flat', max_length=20)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('processing_fee_type', models.CharField(choices=[('flat', 'Flat Amount'), ('percent', 'Percentage')], default='flat', max_length=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('penalty_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('penalty_grace_days', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('product_config', models.JSONField(blank=True, default=dict)),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='workflow.workflow')),
            ],
            options={
                'ordering': ['product_code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_amount__lte', models.F('max_amount'))), name='product_min_lte_max_amount'), models.CheckConstraint(condition=models.Q(('min_tenure__lte', models.F('max_tenure'))), name='product_min_lte_max_tenure')],
            },
        ),
    ]
